language: python

python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

env:
  - DJANGO=1.6
  - DJANGO=1.7
  - DJANGO=1.8
  - DJANGO=1.9

services:
  - redis-server

install:
  - pip install -q django~=$DJANGO.0
  - pip install coveralls
  - pip install mockredispy
  - pip install celery
  - python setup.py develop

script:
  - PYTHONPATH=$PYTHONPATH:$PWD coverage run --source=defender $(which django-admin.py) test defender --settings=defender.travis_settings
  - coverage report -m

matrix:
  exclude:
    - python: "2.6"
      env: DJANGO=1.7
    - python: "2.6"
      env: DJANGO=1.8
    - python: "2.6"
      env: DJANGO=1.9
    - python: "3.3"
      env: DJANGO=1.9
    - python: "3.5"
      env: DJANGO=1.6
    - python: "3.5"
      env: DJANGO=1.7
    - python: "3.6"
      env: DJANGO=1.6
    - python: "3.6"
      env: DJANGO=1.7

after_success:
  - coveralls --verbose
