language: python

python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "pypy"

env:
  - DJANGO=Django==1.6.11
  - DJANGO=Django==1.7.8
  - DJANGO=Django==1.8.2

services:
  - redis-server

install:
  - pip install -q $DJANGO
  - pip install coveralls
  - pip install mockredispy
  - pip install celery
  - python setup.py develop

script:
  - PYTHONPATH=$PYTHONPATH:$PWD coverage run --source=defender $(which django-admin.py) test defender --settings=defender.travis_settings
  - coverage report -m

matrix:
  exclude:
    - python: "2.6"
      env: DJANGO=Django==1.7.7

after_success:
  - coveralls --verbose
